### ISSUE TITLE
Hamburger menu for the navigation bar

### ISSUE THREAD

**Issue by batunpc** [batunpc/Steakhouse#1]
I am trying to make my application mobile responsive, therefore, I want to have my navigation bar links disappear and go under "Burger Menu" icon [see here](https://cdn3.iconfinder.com/data/icons/menu-icons-1/100/menu-512.png). So far, I have accomplished to make the links disappear and leave only certain icons on the right hand side. Now that I want nav links to remain under burger menu icon at the very left of the navigation bar.

To have better understanding, before you look at the source code you can launch the app from the environments section. This app has been published via heroku

**Comment by batunpc** [comment]
https://stark-crag-53181.herokuapp.com/
To see it in practice adjust the responsive design mode to 780-1200

**Comment by mrgeraffe-kun** [comment]
Is someone working on this or is it open to work on?

**Comment by batunpc** [comment]
feel free to work on this project 🔥
